Initial commit for the new SF end point
Crown-Commercial-Service/ccs-conclave-api-tests pull request #58
Opened 2021-05-17 08:57 UTC by himaninare

2021-05-17 16:02 UTC, amrutha-sireesh requested changes

2021-05-20 15:43 UTC, amrutha-sireesh requested changes

2021-05-20 15:43 UTC, amrutha-sireesh commented on src/main/java/com/ccs/conclave/api/cii/data/OrgDataProvider.java
> +    public static String getOnlySFIdentifier(SchemeRegistry schemeRegistry) {
This method is no longer used.

2021-05-20 15:43 UTC, amrutha-sireesh commented on src/main/java/com/ccs/conclave/api/cii/verification/VerifyEndpointResponses.java
> +    public static void verifySFRegisteredSchemesAsAdditionalIdentifiers(Response actualRes, SchemeInfo expectedSchemeInfo, int selectedAddIds) {
Is there any difference between this method and verifyRegisteredSchemes()?

2021-05-25 08:26 UTC, himaninare commented on src/main/java/com/ccs/conclave/api/cii/data/OrgDataProvider.java
> +    public static String getOnlySFIdentifier(SchemeRegistry schemeRegistry) {
Removed

2021-05-25 08:35 UTC, himaninare commented on src/main/java/com/ccs/conclave/api/cii/verification/VerifyEndpointResponses.java
> +    public static void verifySFRegisteredSchemesAsAdditionalIdentifiers(Response actualRes, SchemeInfo expectedSchemeInfo, int selectedAddIds) {
verifyRegisteredSchemes checks for the Primary Identifiers along with additional identifiers whereas the verifySFRegisteredSchemesAsAdditionalIdentifiers checks for additional identifiers only thats y i created one more method

2021-05-27 10:50 UTC, amrutha-sireesh approved these changes

2021-05-27 10:50 UTC, merged